# Generated by Django 5.1.4 on 2025-01-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Загаловок')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Тексты',
            },
        ),
        migrations.CreateModel(
            name='Accord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Загаловок')),
                ('text', models.TextField(verbose_name='Текст аккордиона')),
            ],
            options={
                'verbose_name': 'текст аккордиона',
                'verbose_name_plural': 'Тексты аккордиона',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('images', models.ImageField(blank=True, null=True, upload_to='ins_images', verbose_name='Изображение')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'статью',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
