# Generated by Django 5.1.4 on 2025-01-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='ins_images', verbose_name='Изображение в карусели:')),
                ('text', models.TextField(verbose_name='Текст в карусели:')),
            ],
            options={
                'verbose_name': 'анонс',
                'verbose_name_plural': 'Анонсы',
            },
        ),
    ]
