# Generated by Django 5.1.4 on 2025-01-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_carousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'текст о нас', 'verbose_name_plural': 'Тексты о нас'},
        ),
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'анонс в слайдере', 'verbose_name_plural': 'Анонсы в слайдере'},
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'информацию в картах', 'verbose_name_plural': 'Информация в картах'},
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='accord',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='index',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='ins_images', verbose_name='Изображение в картах'),
        ),
        migrations.AlterField(
            model_name='index',
            name='text',
            field=models.TextField(verbose_name='Текст в картах'),
        ),
    ]
